// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: C:/Users/sunwu/Desktop/base/gateway/notebook/24.11/lex.flex

import java.io.File;
import java.io.FileReader;

@SuppressWarnings("fallthrough")
class Lexer {

  public static void main(String[] args) throws Exception {
    FileReader fr = new FileReader("./input.js");
    Lexer lexer = new Lexer(fr);
    Token token = null;
    while ((token =lexer.yylex()) != null) {
      
    }
  }

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\2\22\0\1\1\1\4"+
    "\3\0\1\5\1\6\1\0\1\7\1\10\1\11\1\12"+
    "\1\13\1\14\1\15\1\16\12\17\1\0\1\20\1\21"+
    "\1\22\1\23\2\0\4\24\1\25\25\24\1\26\1\0"+
    "\1\27\1\30\1\24\1\0\1\31\1\24\1\32\1\24"+
    "\1\33\1\34\1\24\1\35\1\36\2\24\1\37\1\24"+
    "\1\40\1\41\2\24\1\42\1\43\1\44\1\45\1\46"+
    "\1\47\3\24\1\50\1\51\1\52\1\53\6\0\1\3"+
    "\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\1\1\14\1\15\1\16"+
    "\1\17\1\20\1\21\1\22\1\23\1\24\1\25\7\22"+
    "\1\26\1\27\1\30\1\31\1\32\1\33\1\34\1\35"+
    "\1\36\1\15\1\0\1\37\1\40\2\0\1\41\1\42"+
    "\1\43\1\44\1\45\3\22\1\46\4\22\1\47\2\0"+
    "\1\50\5\22\1\51\1\22\1\52\1\53\2\22\1\54"+
    "\3\22\1\55\1\22\1\56\1\22\1\57";

  private static int [] zzUnpackAction() {
    int [] result = new int[82];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\54\0\130\0\204\0\54\0\260\0\54\0\54"+
    "\0\334\0\u0108\0\54\0\u0134\0\u0160\0\u018c\0\u01b8\0\54"+
    "\0\u01e4\0\u0210\0\u023c\0\u0268\0\54\0\54\0\54\0\u0294"+
    "\0\u02c0\0\u02ec\0\u0318\0\u0344\0\u0370\0\u039c\0\54\0\u03c8"+
    "\0\54\0\54\0\54\0\54\0\54\0\54\0\54\0\u03f4"+
    "\0\u0420\0\u044c\0\54\0\u0160\0\u0478\0\54\0\54\0\54"+
    "\0\54\0\54\0\u04a4\0\u04d0\0\u04fc\0\u0268\0\u0528\0\u0554"+
    "\0\u0580\0\u05ac\0\54\0\u05d8\0\u0604\0\u0604\0\u0630\0\u065c"+
    "\0\u0688\0\u06b4\0\u06e0\0\u0268\0\u070c\0\54\0\u0268\0\u0738"+
    "\0\u0764\0\u0268\0\u0790\0\u07bc\0\u07e8\0\u0268\0\u0814\0\u0268"+
    "\0\u0840\0\u0268";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[82];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\2\3\1\0\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\17\1\20"+
    "\1\21\1\22\1\23\2\24\1\25\1\26\1\27\2\24"+
    "\1\30\1\31\1\24\1\32\3\24\1\33\1\24\1\34"+
    "\1\24\1\35\1\36\1\37\1\40\1\41\1\42\55\0"+
    "\2\3\73\0\1\43\37\0\1\44\67\0\1\45\53\0"+
    "\1\46\53\0\1\47\50\0\1\50\45\0\1\51\4\0"+
    "\1\52\3\0\1\53\46\0\1\54\1\0\1\17\5\0"+
    "\1\55\5\0\1\55\41\0\1\56\1\57\53\0\1\60"+
    "\53\0\1\61\1\62\47\0\1\24\4\0\2\24\3\0"+
    "\17\24\23\0\1\24\4\0\2\24\3\0\6\24\1\63"+
    "\10\24\23\0\1\24\4\0\2\24\3\0\1\64\13\24"+
    "\1\65\2\24\23\0\1\24\4\0\2\24\3\0\3\24"+
    "\1\66\13\24\23\0\1\24\4\0\2\24\3\0\2\24"+
    "\1\67\14\24\23\0\1\24\4\0\2\24\3\0\11\24"+
    "\1\70\5\24\23\0\1\24\4\0\2\24\3\0\1\71"+
    "\16\24\23\0\1\24\4\0\2\24\3\0\4\24\1\72"+
    "\12\24\55\0\1\73\21\0\1\50\5\0\1\55\5\0"+
    "\1\55\20\0\11\51\1\74\42\51\2\52\2\0\50\52"+
    "\12\0\1\75\1\0\1\75\2\0\1\76\53\0\1\24"+
    "\4\0\2\24\3\0\12\24\1\77\4\24\23\0\1\24"+
    "\4\0\2\24\3\0\6\24\1\100\10\24\23\0\1\24"+
    "\4\0\2\24\3\0\7\24\1\101\7\24\23\0\1\24"+
    "\4\0\2\24\3\0\13\24\1\102\3\24\23\0\1\24"+
    "\4\0\2\24\3\0\14\24\1\103\2\24\23\0\1\24"+
    "\4\0\2\24\3\0\11\24\1\104\5\24\23\0\1\24"+
    "\4\0\2\24\3\0\5\24\1\105\11\24\4\0\11\51"+
    "\1\74\4\51\1\106\35\51\17\0\1\76\53\0\1\24"+
    "\4\0\2\24\3\0\2\24\1\107\14\24\23\0\1\24"+
    "\4\0\2\24\3\0\12\24\1\103\4\24\23\0\1\24"+
    "\4\0\2\24\3\0\1\24\1\110\15\24\23\0\1\24"+
    "\4\0\2\24\3\0\14\24\1\111\2\24\23\0\1\24"+
    "\4\0\2\24\3\0\2\24\1\112\14\24\23\0\1\24"+
    "\4\0\2\24\3\0\6\24\1\113\10\24\23\0\1\24"+
    "\4\0\2\24\3\0\13\24\1\114\3\24\23\0\1\24"+
    "\4\0\2\24\3\0\11\24\1\115\5\24\23\0\1\24"+
    "\4\0\2\24\3\0\2\24\1\116\14\24\23\0\1\24"+
    "\4\0\2\24\3\0\5\24\1\117\11\24\23\0\1\24"+
    "\4\0\2\24\3\0\7\24\1\120\7\24\23\0\1\24"+
    "\4\0\2\24\3\0\10\24\1\121\6\24\23\0\1\24"+
    "\4\0\2\24\3\0\7\24\1\122\7\24\4\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[2156];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\1\11\1\1\2\11\2\1\1\11"+
    "\4\1\1\11\4\1\3\11\7\1\1\11\1\1\7\11"+
    "\1\1\1\0\1\1\1\11\2\0\5\11\10\1\1\11"+
    "\2\0\10\1\1\11\14\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[82];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    public static class Token {
        public enum Type {
            VAR, FUNCTION, RETURN, IF, ELSE, WHILE,
            
            IDENTIFIER, NUMBER, BOOLEAN,
            
            PLUS, MINUS, MULTIPLY, DIVIDE, MODULO,
            ASSIGN, PLUS_ASSIGN, MINUS_ASSIGN, MULTIPLY_ASSIGN, DIVIDE_ASSIGN,
            
            EQUAL, NOT_EQUAL, LESS_THAN, GREATER_THAN, 
            LESS_OR_EQUAL, GREATER_OR_EQUAL,
            
            LOGICAL_AND, LOGICAL_OR, LOGICAL_NOT,
            
            BITWISE_AND, BITWISE_OR, BITWISE_XOR, 
            BITWISE_NOT, LEFT_SHIFT, RIGHT_SHIFT,
            
            LPAREN, RPAREN, LBRACE, RBRACE, 
            LBRACKET, RBRACKET, COMMA, SEMICOLON,
            
            ERROR, EOF
        }

        public Type type;
        public String value;
        public int line;
        public int column;

        public Token(Type type, String value, int line, int column) {
            this.type = type;
            this.value = value;
            this.line = line;
            this.column = column;
        }

        @Override
        public String toString() {
            return String.format("%s: %s (Line: %d, Column: %d)", 
                type, value, line, column);
        }
    }


    private void log(String category, String value) {
        System.out.printf("%s: %s\n", category, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
              {
                return null;
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { log("UNEXPECTED CHARACTER", yytext());
    return new Token(Token.Type.ERROR, yytext(), yyline, yycolumn);
            }
          // fall through
          case 48: break;
          case 2:
            { /* 忽略空白 */
            }
          // fall through
          case 49: break;
          case 3:
            { log("LOGICAL", yytext());
    return new Token(Token.Type.LOGICAL_NOT, yytext(), yyline, yycolumn);
            }
          // fall through
          case 50: break;
          case 4:
            { log("ARITHMETIC", yytext());
    return new Token(Token.Type.MODULO, yytext(), yyline, yycolumn);
            }
          // fall through
          case 51: break;
          case 5:
            { log("BITWISE", yytext());
    return new Token(Token.Type.BITWISE_AND, yytext(), yyline, yycolumn);
            }
          // fall through
          case 52: break;
          case 6:
            { log("DELIMITER", yytext());
    return new Token(Token.Type.LPAREN, yytext(), yyline, yycolumn);
            }
          // fall through
          case 53: break;
          case 7:
            { log("DELIMITER", yytext());
    return new Token(Token.Type.RPAREN, yytext(), yyline, yycolumn);
            }
          // fall through
          case 54: break;
          case 8:
            { log("ARITHMETIC", yytext());
    return new Token(Token.Type.MULTIPLY, yytext(), yyline, yycolumn);
            }
          // fall through
          case 55: break;
          case 9:
            { log("ARITHMETIC", yytext());
    return new Token(Token.Type.PLUS, yytext(), yyline, yycolumn);
            }
          // fall through
          case 56: break;
          case 10:
            { log("DELIMITER", yytext());
    return new Token(Token.Type.COMMA, yytext(), yyline, yycolumn);
            }
          // fall through
          case 57: break;
          case 11:
            { log("ARITHMETIC", yytext());
    return new Token(Token.Type.MINUS, yytext(), yyline, yycolumn);
            }
          // fall through
          case 58: break;
          case 12:
            { log("ARITHMETIC", yytext());
    return new Token(Token.Type.DIVIDE, yytext(), yyline, yycolumn);
            }
          // fall through
          case 59: break;
          case 13:
            { String category = yytext().contains(".") ? "NUMBER (FLOAT)" : "NUMBER (INTEGER)";
    log(category, yytext());
    return new Token(Token.Type.NUMBER, yytext(), yyline, yycolumn);
            }
          // fall through
          case 60: break;
          case 14:
            { log("DELIMITER", yytext());
    return new Token(Token.Type.SEMICOLON, yytext(), yyline, yycolumn);
            }
          // fall through
          case 61: break;
          case 15:
            { log("COMPARISON", yytext());
    return new Token(Token.Type.LESS_THAN, yytext(), yyline, yycolumn);
            }
          // fall through
          case 62: break;
          case 16:
            { log("ASSIGNMENT", yytext());
    return new Token(Token.Type.ASSIGN, yytext(), yyline, yycolumn);
            }
          // fall through
          case 63: break;
          case 17:
            { log("COMPARISON", yytext());
    return new Token(Token.Type.GREATER_THAN, yytext(), yyline, yycolumn);
            }
          // fall through
          case 64: break;
          case 18:
            { log("IDENTIFIER", yytext());
    return new Token(Token.Type.IDENTIFIER, yytext(), yyline, yycolumn);
            }
          // fall through
          case 65: break;
          case 19:
            { log("DELIMITER", yytext());
    return new Token(Token.Type.LBRACKET, yytext(), yyline, yycolumn);
            }
          // fall through
          case 66: break;
          case 20:
            { log("DELIMITER", yytext());
    return new Token(Token.Type.RBRACKET, yytext(), yyline, yycolumn);
            }
          // fall through
          case 67: break;
          case 21:
            { log("BITWISE", yytext());
    return new Token(Token.Type.BITWISE_XOR, yytext(), yyline, yycolumn);
            }
          // fall through
          case 68: break;
          case 22:
            { log("DELIMITER", yytext());
    return new Token(Token.Type.LBRACE, yytext(), yyline, yycolumn);
            }
          // fall through
          case 69: break;
          case 23:
            { log("BITWISE", yytext());
    return new Token(Token.Type.BITWISE_OR, yytext(), yyline, yycolumn);
            }
          // fall through
          case 70: break;
          case 24:
            { log("DELIMITER", yytext());
    return new Token(Token.Type.RBRACE, yytext(), yyline, yycolumn);
            }
          // fall through
          case 71: break;
          case 25:
            { log("BITWISE", yytext());
    return new Token(Token.Type.BITWISE_NOT, yytext(), yyline, yycolumn);
            }
          // fall through
          case 72: break;
          case 26:
            { log("COMPARISON", yytext());
    return new Token(Token.Type.NOT_EQUAL, yytext(), yyline, yycolumn);
            }
          // fall through
          case 73: break;
          case 27:
            { log("LOGICAL", yytext());
    return new Token(Token.Type.LOGICAL_AND, yytext(), yyline, yycolumn);
            }
          // fall through
          case 74: break;
          case 28:
            { log("ASSIGNMENT", yytext());
    return new Token(Token.Type.MULTIPLY_ASSIGN, yytext(), yyline, yycolumn);
            }
          // fall through
          case 75: break;
          case 29:
            { log("ASSIGNMENT", yytext());
    return new Token(Token.Type.PLUS_ASSIGN, yytext(), yyline, yycolumn);
            }
          // fall through
          case 76: break;
          case 30:
            { log("ASSIGNMENT", yytext());
    return new Token(Token.Type.MINUS_ASSIGN, yytext(), yyline, yycolumn);
            }
          // fall through
          case 77: break;
          case 31:
            { /* 忽略单行注释 */
            }
          // fall through
          case 78: break;
          case 32:
            { log("ASSIGNMENT", yytext());
    return new Token(Token.Type.DIVIDE_ASSIGN, yytext(), yyline, yycolumn);
            }
          // fall through
          case 79: break;
          case 33:
            { log("BITWISE", yytext());
    return new Token(Token.Type.LEFT_SHIFT, yytext(), yyline, yycolumn);
            }
          // fall through
          case 80: break;
          case 34:
            { log("COMPARISON", yytext());
    return new Token(Token.Type.LESS_OR_EQUAL, yytext(), yyline, yycolumn);
            }
          // fall through
          case 81: break;
          case 35:
            { log("COMPARISON", yytext());
    return new Token(Token.Type.EQUAL, yytext(), yyline, yycolumn);
            }
          // fall through
          case 82: break;
          case 36:
            { log("COMPARISON", yytext());
    return new Token(Token.Type.GREATER_OR_EQUAL, yytext(), yyline, yycolumn);
            }
          // fall through
          case 83: break;
          case 37:
            { log("BITWISE", yytext());
    return new Token(Token.Type.RIGHT_SHIFT, yytext(), yyline, yycolumn);
            }
          // fall through
          case 84: break;
          case 38:
            { log("KEYWORD", yytext());
    return new Token(Token.Type.IF, yytext(), yyline, yycolumn);
            }
          // fall through
          case 85: break;
          case 39:
            { log("LOGICAL", yytext());
    return new Token(Token.Type.LOGICAL_OR, yytext(), yyline, yycolumn);
            }
          // fall through
          case 86: break;
          case 40:
            { log("NUMBER (SCIENTIFIC)", yytext());
    return new Token(Token.Type.NUMBER, yytext(), yyline, yycolumn);
            }
          // fall through
          case 87: break;
          case 41:
            { log("KEYWORD", yytext());
    return new Token(Token.Type.VAR, yytext(), yyline, yycolumn);
            }
          // fall through
          case 88: break;
          case 42:
            { /* 忽略多行注释 */
            }
          // fall through
          case 89: break;
          case 43:
            { log("KEYWORD", yytext());
    return new Token(Token.Type.ELSE, yytext(), yyline, yycolumn);
            }
          // fall through
          case 90: break;
          case 44:
            { log("BOOLEAN", yytext());
    return new Token(Token.Type.BOOLEAN, yytext(), yyline, yycolumn);
            }
          // fall through
          case 91: break;
          case 45:
            { log("KEYWORD", yytext());
    return new Token(Token.Type.WHILE, yytext(), yyline, yycolumn);
            }
          // fall through
          case 92: break;
          case 46:
            { log("KEYWORD", yytext());
    return new Token(Token.Type.RETURN, yytext(), yyline, yycolumn);
            }
          // fall through
          case 93: break;
          case 47:
            { log("KEYWORD", yytext());
    return new Token(Token.Type.FUNCTION, yytext(), yyline, yycolumn);
            }
          // fall through
          case 94: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
