import { Inter } from "next/font/google";
import NavBar from "@/app/components/navbar-menu";
import "./globals.css";
import "./prism-dracula.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/github-markdown-css/4.0.0/github-markdown.min.css" />
      </head>
      <body className={inter.className + '  container mx-[auto] max-w-[80%]'}>
        <div className="relative w-full flex items-center justify-center bg-yellow-400">
          <NavBar className="top-2" />
        </div>
        <div className="markdown-body mt-20">{children}</div>
      </body>
    </html>
  );
}
