/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jvmti_JVMTIDemo */

#ifndef _Included_com_jvmti_JVMTIDemo
#define _Included_com_jvmti_JVMTIDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jvmti_JVMTIDemo
 * Method:    getInstance
 * Signature: (Ljava/lang/Class;)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_com_jvmti_JVMTIDemo_getInstance
  (JNIEnv *, jobject, jclass);

#ifdef __cplusplus
}
#endif
#endif
