/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RustHttpServer */

#ifndef _Included_RustHttpServer
#define _Included_RustHttpServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     RustHttpServer
 * Method:    startServer
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_RustHttpServer_startServer
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
