/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Main */

#ifndef _Included_Main
#define _Included_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Main
 * Method:    native_hello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Main_native_1hello
  (JNIEnv *, jclass);

/*
 * Class:     Main
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Main_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Main
 * Method:    hi
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Main_hi
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
